### ISSUE TITLE
translations english dutch

### ISSUE THREAD

**Issue by vliegendevogel** [BaldricNetwork/Web#9]
I already translated the rules to english and dutch am i allowed to give the translations here ?

**Comment by RubeVi** [comment]
Do a pull request

**Comment by vliegendevogel** [comment]
I don't have permission to do a pull request, this is the error 

Ronan@Ronan MINGW64 ~/Documents/baldric/Web (master)
$ git push
remote: Permission to BaldricNetwork/Web.git denied to vliegendevogel.
fatal: unable to access 'https://github.com/BaldricNetwork/Web.git/': The requested URL returned error: 403

**Comment by RubeVi** [comment]
Create it via web

**Comment by vliegendevogel** [comment]
https://docs.google.com/document/d/1Iq7VBcp2eJIqJDpDXBwcuVggV57kaMGKupKbB0wY3J0/edit Here it is
